### ISSUE TITLE
Конфиги в репозитории

### ISSUE THREAD

**Issue by dyakubovich** [onetakeone/ADS#1]
Хранить конфиги в репозитории — похая практика:
- не у всех разработчиков одинаковый логины и пароли к бд (можно просто менять параметры в закомиченном файле, но это постоянный риск его случайно закоммитить)
- не у всех разработчиков есть доступ к ключам в сторонние сервисы, которые должны хранится в конфигах
- на продакшне конфиги буду точно другие

 Для всех конфигов нужно создать файлы-примеры в папке `config/examples`, а реальные файлы конфиги удаляются из репозитория и добавляются в `.gitignore`.

**Comment by onetakeone** [comment]
initializers, как я понимаю, нужно оставлять?

**Comment by dyakubovich** [comment]
Да, но значение различных ключей лучше подключать через ENV

**Comment by dyakubovich** [comment]
https://github.com/onetakeone/ADS/commit/8ce5f5bf0fccb7b4e116f2b7acbf4bb250178f1f
Нужно вернуть файлы с расширением .rb

**Comment by onetakeone** [comment]
.env добавил. Конечно, было бы здорово посмотреть на рабочий репозиторий и организацию конфигов для разных сред в рабочем проекте.
