### ISSUE TITLE
Автор объявления

### ISSUE THREAD

**Issue by dyakubovich** [onetakeone/ADS#11]
https://github.com/onetakeone/ADS/blob/master/app/views/ads/index.html.erb#L28
Излишений запрос. Имя пользователя можно получать по-другому, так как пользователь связан с моделью объявок связью один ко многим. Подумай как это реализовать по-другому, не используя поиск по пользователям.  Из экшена index  нужно убрать @users = User.all и реализовать отображения автора по-другому.

**Comment by onetakeone** [comment]
ad.user.username - вот за такое стоит любить Ruby!
