### ISSUE TITLE
Декоратор

### ISSUE THREAD

**Issue by dyakubovich** [onetakeone/ADS#12]
во вьюхах повторяющиеся модификации над данными нужно выносить в helper'ы или использовать декораторы (https://github.com/drapergem/draper)

**Comment by onetakeone** [comment]
Сделал хелперы для ссылок и кнопок.

Принципы DRY обязательны для проектов любого объема?
Грубо говоря, когда в моем проекте всего пять страниц, с ними проще работать без дробления, хелперов и, возможно, партиалов. 
Уместно ли по собственному усмотрению отклоняться в сторону удобства разработки, или стоит строго следовать концепции минимализма и структуризации в коде, чтобы потом не заплевали коллеги?

**Comment by dyakubovich** [comment]
Если есть 100% уверенность  что проект не будет развивваться, то иногда можно, но опять же, держать всю логику на странице это не удобно и не правильно, лучше когда все красиво и понятно, чем например искать что-то на странице, в которой 300 строк
