### ISSUE TITLE
Ошибки в тестах

### ISSUE THREAD

**Issue by dyakubovich** [onetakeone/ADS#15]
Запустил тесты, все упали.  Давай самый критичный функционал покроем интеграционными тестами:

- создание и редактирование объявки;
- изменение статуса объявки админом;
- сортировка объявок;
- фильтрация объявок по категориям.

**Comment by onetakeone** [comment]
rspec тесты работали) 
сделал фильтрацию с сортировкой, написал тесты к ним.

**Comment by dyakubovich** [comment]
https://github.com/onetakeone/ADS/blob/master/spec/factories/users.rb#L24
Нужно убрать дублирование кода (:writer_one, :writer_two) - для этого достаточно создать  только один factory :write , и в нем подставлять различные данные. Для генарации фейковых данных можно использовать gem 'faker' . Id в factory не должны задаваться, пересмотри пожалуйста документацию для этого гема

**Comment by onetakeone** [comment]
Я запишу ошибку, если вдруг сам не разберусь, и найдётся время - буду рад помощи) 
Смысл в том что тестовая оболочка не видит результата фильтрации. Прочекал и прокликал чекбоксы всем чем можно. Для простоты тут создал модели ручками:

````
scenario 'show advert matching to the type' do
    @ada = FactoryGirl.create(:published)
    @adb = FactoryGirl.create(:published)
    visit '/ads'
    find(:css, "#0[value='1']").set(true)
    # page.check @ada.type.ad_type
    # check "1"
    click_on 'search_button'
    expect(page).to have_content @ada.body
    # expect(page).to have_content '1111'
    # expect(page).to have_no_content @adb.body
  end

1) Filter show advert matching to the type
     Failure/Error: expect(page).to have_content @ada.body
       expected to find text "Vel occaecati saepe nobis dolorem molestiae." in "HomeAdvertsAdvertsSessionLoginRegisterAdvertisementsrerum ( 1 )dolores ( 1 )sort by:Title Released"
     # ./spec/features/default_filter_spec.rb:24:in `block (2 levels) in <top (required)>'

**Comment by onetakeone** [comment]
Причём такой сценарий работает, значит что-то не то чекает. 
```` 
scenario 'blabla' do
    user = User.create(id: 1, username: 'user', email: 'email@em.em', password: 'asfasdff')
    typea = Type.create(id: 1, ad_type: 'typea')
    typeb = Type.create(id: 2, ad_type: 'typeb')
    ada = Ad.create(title: 'titlea', body: 'bodya', id: 1, type_id: 1, user_id: 1, state: 'published')
    adb = Ad.create(title: 'titleb', body: 'bodyb', id: 2, type_id: 2, user_id: 1, state: 'published')
    visit '/ads/'
    check 'typea'
    click_on 'search_button'
    expect(page).to have_content 'titlea'
    expect(page).to have_no_content 'titleb'
    check 'typeb'
    click_on 'search_button'
    expect(page).to have_content 'titleb'
    expect(page).to have_no_content 'titlea'
  end
````

**Comment by onetakeone** [comment]
Сделал
