### ISSUE TITLE
Сортировка и поиск через ajax

### ISSUE THREAD

**Issue by dyakubovich** [onetakeone/ADS#20]
Реализовать сортировку по цене и названию. Реализовать поиск через ajax.

**Comment by onetakeone** [comment]
С ajax залип сильно.
Хотел взять этот каст за основу http://railscasts.com/episodes/240-search-sort-paginate-with-ajax и допилить его под проект, но нормально он не взлетает (интегрировал в проект, запускал отдельным приложением, запускал на убунту). 
Поиск и сортировка не видят друг друга - нельзя сортировать результаты поиска. 
Плюс с параметром remote: true в таблице вьюхи объявок поиск вообще не работает.
Есть идеи куда смотреть? Предполагаю что в скрипте: 
 ````
$(function() {
  $('#ads th a, #ads .pagination a').on('click', function() {
    $.getScript(this.href);
    return false;
  });
  $('#ads_search input').keyup(function() {
    $.get($('#ads_search').attr('action'), $('#ads_search').serialize(), null, 'script');
    return false;
  });
});
````
И в хелпере проблема:
````
link_to title, params.merge(sort: column, direction: direction, page: nil).permit(:sort, :direction, :page), {class: css_class}
````

**Comment by onetakeone** [comment]
Сортировку результата поиска пофиксил. Ajax всё ещё не запустил..

**Comment by onetakeone** [comment]
Вопрос: 
Не рендерятся такого плана скрипты (и под win, и в unix). 
``$('#link').hide().after('<%= j render("form") %>');``
``$('#tasks').append('<%= j render(@task) %>')``
``$("#ads").html('<%= j render("ads") %>');``

Не могу разобраться третий день )

**Comment by onetakeone** [comment]
В итоге нужно было удалить ссылку на script jquery из шапки.
Поиск + сортировка (сделал сортировку по дате)
