### ISSUE TITLE
Рефакторинг поиска

### ISSUE THREAD

**Issue by dyakubovich** [onetakeone/ADS#21]
Нужно реализовать полнотекстовый поиск. Можешь использовать  postgres fulltext search .
На будущее https://github.com/onetakeone/ADS/blob/master/app/models/ad.rb#L53 - такие запросы нужно выносить в скоупы.

https://github.com/onetakeone/ADS/blob/master/app/models/ad.rb#L50 
https://github.com/onetakeone/ADS/blob/master/app/models/ad.rb#L51 -
такая проверка лишняя, так как нужно проверять поле search перед этим выражениям, на 51 строчке.
Еще search.to_s - не нужно преобразовывать в строку,  ActiveRecord сделает это за тебя. 
state = 'published' - так тоже лучше не делать, нужно все переменные выносить из запроса.

**Comment by onetakeone** [comment]
Переехал на постгрес. Поиск отрефакторил и сделал full text.

**Comment by dyakubovich** [comment]
https://github.com/Casecommons/pg_search поиск лучше реализуй через этот гем

**Comment by onetakeone** [comment]
сделал
