### ISSUE TITLE
Добавить фильтрацию по Типам

### ISSUE THREAD

**Issue by dyakubovich** [onetakeone/ADS#22]
При отображении списка объявления нужно выводить список всех типов с количеством объявлений для каждого типа. Типы выводить в виде чекбоксов. Дать возможность пользователю выбрать нужные типа и применить (можно добавить кнопку "Применить" либо обновлять объявки динамически) , после выбора типов, отобразить объявки, которые соответствуют заданному фильтру. Это нужно реализовать использую ajax

**Comment by onetakeone** [comment]
Логика должна быть в jquery по заданию? Или это следующий шаг будет?)  
Подкинул чекбоксы в форму поиска, метод в модель, работает через ajax.
