### ISSUE TITLE
Версия руби

### ISSUE THREAD

**Issue by dyakubovich** [onetakeone/ADS#3]
Для того, чтобы у всех разработчиков была одна версия руби — нужно  в репозитории хранить файл .ruby-version с номером версии текущей руби.
Но не нужно этот файл создавать вручную, rvm и rbenv умеют его создавать автоматически.

**Comment by onetakeone** [comment]
проблема в том что проект под windows... 
 
виртуальную машину и ubuntu уже поставил, ковыряю mysql и omniauth )

**Comment by onetakeone** [comment]
всё, теперь под юникс. 
.ruby-version сделал
