### ISSUE TITLE
Файлы-пустышки в репозитории

### ISSUE THREAD

**Issue by dyakubovich** [onetakeone/ADS#4]
В репозитории есть файлы, в которых ничего нет, кроме объявления. Например: 
https://github.com/onetakeone/ADS/blob/master/app/assets/javascripts/ads.coffee
https://github.com/onetakeone/ADS/blob/master/app/assets/stylesheets/ads.scss

Такие файлы нужно удалять, иначе они отвлекают на себя внимание. Но недостаточно их просто удалить. При генерации новых сущностей они все равно будут создаваться. Поэтому, генерацию хэлперов, ассетов, тестов и, возможно, чего-то еще нужно отключить.

**Comment by onetakeone** [comment]
Для этого можно настроить генератор в конфиге. 
`  config.generators do |g|
      g.test_framework  false
      g.test_unit       false
      g.assets          false
      g.helper          false
      g.jbuilder        false      
    end`

Вопрос, TestUnit тесты вообще отключать и удалять уже сгенерированные ранее?

**Comment by dyakubovich** [comment]
Сгенерированные пустые файлы удаляй, если в них не будет тестов

**Comment by dyakubovich** [comment]
Сейчас у тебя для тестов используется  Rspec и test. Нужно оставить что-то одно,  остальное удалить

**Comment by onetakeone** [comment]
Сделал
