### ISSUE TITLE
Сиды

### ISSUE THREAD

**Issue by dyakubovich** [onetakeone/ADS#5]
`user = User.new
user.id = 1
user.username = 'admin'
user.role = 'admin'
user.email = 'admin@admin'
user.password = 'passpass'
user.password_confirmation = 'passpass'
user.save!`
В сидах не нужно в ручную указывать id - это поле генерируется само, исходя из записей в базе данных. Задавать поля  и сразу сохранять можно одной командой, подумай как

**Comment by onetakeone** [comment]
Создавать поле сразу - create, а id вручную в данном случае указаны для привязки постов к конкретным пользователям и типам )
