### ISSUE TITLE
Стиль кода

### ISSUE THREAD

**Issue by dyakubovich** [onetakeone/ADS#7]
Добавить и запустить rubycop и проверить весь код по стилю

**Comment by onetakeone** [comment]
1. Длина строки считается критическим критерием при форматировании кода?
2. Принято ли прорабатывать стиль кода в сторонних гем-файлах и в тех что генерирует rails?   
3. Окончание строки CR / LF, как я понимаю, тоже не критично

**Comment by dyakubovich** [comment]
1) Желательно делать строки соответствующей длины, это делает код более читабальным
2)  Да, лучше придерживаться стилю
3) Да
