### ISSUE TITLE
Авторизация действий

### ISSUE THREAD

**Issue by dyakubovich** [onetakeone/ADS#8]
Сейчас любой пользователь может отредактировать объявления другого пользователя. Так быть не должно. Прочитай и хорошо разберись как работает https://github.com/CanCanCommunity/cancancan
Также любой пользователь может зайти на страницу http://localhost:3000/types и отредактировать, создать тип. Эти действия должен выполнять только админ

**Comment by onetakeone** [comment]
Отредактировал модель Ability, прописал authorize! в контроллерах

**Comment by dyakubovich** [comment]
Прочитай еще раз внимательно документацию гема. Особое внимание обрати на метод  load_and_authorize_resource -  разберись как он работает

**Comment by onetakeone** [comment]
Сначала load_and_authorize_resource не срабатывал. Оказалось из-за некорректной версии cancan (1.6).
Сделал.
